name: qcarder
description: Digital business cards are the modern solution for exchanging contact information and nurturing client relationships. Unlike traditional paper cards, these dynamic and efficient tools offer immediate access to essential details, such as websites, product portfolios, and social media profiles. This not only enhances professionalism but also streamlines follow-up actions, leading to more effective sales conversions.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.1+11

environment:
  sdk: ">=2.19.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.5
  shared_preferences: ^2.2.3
  equatable: ^2.0.5
  get_it: ^7.7.0
  flutter_dotenv: ^5.1.0
  flutter_svg: ^2.0.10+1
  image_picker: ^1.1.2
  infinite_scroll_pagination: ^4.0.0
  jwt_decoder: ^2.0.1
  country_code_picker: ^3.0.0
  url_launcher: ^6.2.6
  nfc_manager: ^3.5.0
  http: ^1.2.1
  http_parser: ^4.0.2
  rename: ^3.0.2
  cached_network_image: ^3.3.1
  package_info_plus: ^8.0.0
  webview_flutter: ^4.8.0

  # firebase FIXME: deprecated, remove it
  firebase_dynamic_links: ^5.3.4

  # open api
  openapi_generator_annotations: ^5.0.2
  openapi_generator_cli: ^5.0.2
  qcarder_api:
    path: apis

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

  # open api
  openapi_generator: ^5.0.2
  build_runner: ^2.4.9
  dart_style: ^2.3.6
  build_test: ^2.2.2
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/q.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/q.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/q.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/q.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/links/
    - assets/icons/flags/
    - .env.development
    - .env.production

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/inter/Inter-Thin.ttf
          weight: 300
        - asset: assets/fonts/inter/Inter-Light.ttf
          weight: 400
        - asset: assets/fonts/inter/Inter-Regular.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter-Medium.ttf
          weight: 600
        - asset: assets/fonts/inter/Inter-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Thin.ttf
          weight: 300
        - asset: assets/fonts/roboto/Roboto-Light.ttf
          weight: 400
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
          weight: 500
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
          weight: 600
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700
