name: qcarder
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.1.1
  equatable: ^2.0.5
  get_it: ^7.6.0
  flutter_dotenv: ^5.1.0
  flutter_svg: ^2.0.7
  image_picker: ^0.8.7+5
  # intl: ^0.17.1
  # http: ^1.0.0
  infinite_scroll_pagination: ^3.2.0
  jwt_decoder: ^2.0.1
  country_code_picker: ^3.0.0
  url_launcher: ^6.1.11
  nfc_manager: ^3.3.0
  http_parser: ^4.0.2

  # open api
  openapi_generator_annotations: ^4.10.0
  qcarder_api:
    path: apis

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

  # open api
  openapi_generator: ^4.10.0
  build_runner: ^2.4.1
  dart_style: ^2.3.1
  build_test: ^2.1.7
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/q.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/q.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/q.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/q.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/links/
    - assets/icons/flags/
    - .env.development
    - .env.production

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/inter/Inter-Thin.ttf
          weight: 300
        - asset: assets/fonts/inter/Inter-Light.ttf
          weight: 400
        - asset: assets/fonts/inter/Inter-Regular.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter-Medium.ttf
          weight: 600
        - asset: assets/fonts/inter/Inter-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Thin.ttf
          weight: 300
        - asset: assets/fonts/roboto/Roboto-Light.ttf
          weight: 400
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
          weight: 500
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
          weight: 600
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700
